on:
  push:
    branches:
      - master
  pull_request:
name: upper-bound-check
jobs:
  upper-bound-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: java -version
      - name: Install the BOM to local Maven repository
        run: .kokoro/build.sh
      - name: Check the BOM content satisfies the upper-bound-check test case
        run: mvn -B -V -ntp verify -Dcheckstyle.skip
        working-directory: upper-bound-check
