// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/location/locations.proto

package com.google.cloud.location;

public interface GetLocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.location.GetLocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name for the location.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Resource name for the location.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
