/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iam/v2/policy.proto

// Protobuf Java Version: 3.25.5
package com.google.iam.v2;

/**
 *
 *
 * <pre>
 * Data for an IAM policy.
 * </pre>
 *
 * Protobuf type {@code google.iam.v2.Policy}
 */
public final class Policy extends com.google.protobuf.GeneratedMessageLite<Policy, Policy.Builder>
    implements
    // @@protoc_insertion_point(message_implements:google.iam.v2.Policy)
    PolicyOrBuilder {
  private Policy() {
    name_ = "";
    uid_ = "";
    kind_ = "";
    displayName_ = "";
    etag_ = "";
    rules_ = emptyProtobufList();
    managingAuthority_ = "";
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   *
   *
   * <pre>
   * Immutable. The resource name of the `Policy`, which must be unique. Format:
   * `policies/{attachment_point}/denypolicies/{policy_id}`
   *
   *
   * The attachment point is identified by its URL-encoded full resource name,
   * which means that the forward-slash character, `/`, must be written as
   * `%2F`. For example,
   * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
   *
   * For organizations and folders, use the numeric ID in the full resource
   * name. For projects, requests can use the alphanumeric or the numeric ID.
   * Responses always contain the numeric ID.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   *
   *
   * <pre>
   * Immutable. The resource name of the `Policy`, which must be unique. Format:
   * `policies/{attachment_point}/denypolicies/{policy_id}`
   *
   *
   * The attachment point is identified by its URL-encoded full resource name,
   * which means that the forward-slash character, `/`, must be written as
   * `%2F`. For example,
   * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
   *
   * For organizations and folders, use the numeric ID in the full resource
   * name. For projects, requests can use the alphanumeric or the numeric ID.
   * Responses always contain the numeric ID.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   *
   *
   * <pre>
   * Immutable. The resource name of the `Policy`, which must be unique. Format:
   * `policies/{attachment_point}/denypolicies/{policy_id}`
   *
   *
   * The attachment point is identified by its URL-encoded full resource name,
   * which means that the forward-slash character, `/`, must be written as
   * `%2F`. For example,
   * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
   *
   * For organizations and folders, use the numeric ID in the full resource
   * name. For projects, requests can use the alphanumeric or the numeric ID.
   * Responses always contain the numeric ID.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @param value The name to set.
   */
  private void setName(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    name_ = value;
  }
  /**
   *
   *
   * <pre>
   * Immutable. The resource name of the `Policy`, which must be unique. Format:
   * `policies/{attachment_point}/denypolicies/{policy_id}`
   *
   *
   * The attachment point is identified by its URL-encoded full resource name,
   * which means that the forward-slash character, `/`, must be written as
   * `%2F`. For example,
   * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
   *
   * For organizations and folders, use the numeric ID in the full resource
   * name. For projects, requests can use the alphanumeric or the numeric ID.
   * Responses always contain the numeric ID.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   *
   *
   * <pre>
   * Immutable. The resource name of the `Policy`, which must be unique. Format:
   * `policies/{attachment_point}/denypolicies/{policy_id}`
   *
   *
   * The attachment point is identified by its URL-encoded full resource name,
   * which means that the forward-slash character, `/`, must be written as
   * `%2F`. For example,
   * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
   *
   * For organizations and folders, use the numeric ID in the full resource
   * name. For projects, requests can use the alphanumeric or the numeric ID.
   * Responses always contain the numeric ID.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @param value The bytes for name to set.
   */
  private void setNameBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
  }

  public static final int UID_FIELD_NUMBER = 2;
  private java.lang.String uid_;
  /**
   *
   *
   * <pre>
   * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
   * `Policy` is created.
   * </pre>
   *
   * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @return The uid.
   */
  @java.lang.Override
  public java.lang.String getUid() {
    return uid_;
  }
  /**
   *
   *
   * <pre>
   * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
   * `Policy` is created.
   * </pre>
   *
   * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @return The bytes for uid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getUidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(uid_);
  }
  /**
   *
   *
   * <pre>
   * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
   * `Policy` is created.
   * </pre>
   *
   * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @param value The uid to set.
   */
  private void setUid(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    uid_ = value;
  }
  /**
   *
   *
   * <pre>
   * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
   * `Policy` is created.
   * </pre>
   *
   * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   */
  private void clearUid() {

    uid_ = getDefaultInstance().getUid();
  }
  /**
   *
   *
   * <pre>
   * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
   * `Policy` is created.
   * </pre>
   *
   * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @param value The bytes for uid to set.
   */
  private void setUidBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    uid_ = value.toStringUtf8();
  }

  public static final int KIND_FIELD_NUMBER = 3;
  private java.lang.String kind_;
  /**
   *
   *
   * <pre>
   * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
   * </pre>
   *
   * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The kind.
   */
  @java.lang.Override
  public java.lang.String getKind() {
    return kind_;
  }
  /**
   *
   *
   * <pre>
   * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
   * </pre>
   *
   * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The bytes for kind.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getKindBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(kind_);
  }
  /**
   *
   *
   * <pre>
   * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
   * </pre>
   *
   * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @param value The kind to set.
   */
  private void setKind(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    kind_ = value;
  }
  /**
   *
   *
   * <pre>
   * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
   * </pre>
   *
   * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  private void clearKind() {

    kind_ = getDefaultInstance().getKind();
  }
  /**
   *
   *
   * <pre>
   * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
   * </pre>
   *
   * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @param value The bytes for kind to set.
   */
  private void setKindBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    kind_ = value.toStringUtf8();
  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 4;
  private java.lang.String displayName_;
  /**
   *
   *
   * <pre>
   * A user-specified description of the `Policy`. This value can be up to 63
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   *
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   *
   *
   * <pre>
   * A user-specified description of the `Policy`. This value can be up to 63
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   *
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   *
   *
   * <pre>
   * A user-specified description of the `Policy`. This value can be up to 63
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   *
   * @param value The displayName to set.
   */
  private void setDisplayName(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    displayName_ = value;
  }
  /**
   *
   *
   * <pre>
   * A user-specified description of the `Policy`. This value can be up to 63
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   *
   *
   * <pre>
   * A user-specified description of the `Policy`. This value can be up to 63
   * characters.
   * </pre>
   *
   * <code>string display_name = 4;</code>
   *
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();
  }

  public static final int ANNOTATIONS_FIELD_NUMBER = 5;

  private static final class AnnotationsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntryLite.<java.lang.String, java.lang.String>newDefaultInstance(
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
  }

  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String> annotations_ =
      com.google.protobuf.MapFieldLite.emptyMapField();

  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
      internalGetAnnotations() {
    return annotations_;
  }

  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
      internalGetMutableAnnotations() {
    if (!annotations_.isMutable()) {
      annotations_ = annotations_.mutableCopy();
    }
    return annotations_;
  }

  @java.lang.Override
  public int getAnnotationsCount() {
    return internalGetAnnotations().size();
  }
  /**
   *
   *
   * <pre>
   * A key-value map to store arbitrary metadata for the `Policy`. Keys
   * can be up to 63 characters. Values can be up to 255 characters.
   * </pre>
   *
   * <code>map&lt;string, string&gt; annotations = 5;</code>
   */
  @java.lang.Override
  public boolean containsAnnotations(java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetAnnotations().containsKey(key);
  }
  /** Use {@link #getAnnotationsMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
    return getAnnotationsMap();
  }
  /**
   *
   *
   * <pre>
   * A key-value map to store arbitrary metadata for the `Policy`. Keys
   * can be up to 63 characters. Values can be up to 255 characters.
   * </pre>
   *
   * <code>map&lt;string, string&gt; annotations = 5;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
    return java.util.Collections.unmodifiableMap(internalGetAnnotations());
  }
  /**
   *
   *
   * <pre>
   * A key-value map to store arbitrary metadata for the `Policy`. Keys
   * can be up to 63 characters. Values can be up to 255 characters.
   * </pre>
   *
   * <code>map&lt;string, string&gt; annotations = 5;</code>
   */
  @java.lang.Override
  public /* nullable */ java.lang.String getAnnotationsOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map = internalGetAnnotations();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   *
   *
   * <pre>
   * A key-value map to store arbitrary metadata for the `Policy`. Keys
   * can be up to 63 characters. Values can be up to 255 characters.
   * </pre>
   *
   * <code>map&lt;string, string&gt; annotations = 5;</code>
   */
  @java.lang.Override
  public java.lang.String getAnnotationsOrThrow(java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map = internalGetAnnotations();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   *
   *
   * <pre>
   * A key-value map to store arbitrary metadata for the `Policy`. Keys
   * can be up to 63 characters. Values can be up to 255 characters.
   * </pre>
   *
   * <code>map&lt;string, string&gt; annotations = 5;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String> getMutableAnnotationsMap() {
    return internalGetMutableAnnotations();
  }

  public static final int ETAG_FIELD_NUMBER = 6;
  private java.lang.String etag_;
  /**
   *
   *
   * <pre>
   * An opaque tag that identifies the current version of the `Policy`. IAM uses
   * this value to help manage concurrent updates, so they do not cause one
   * update to be overwritten by another.
   *
   * If this field is present in a [CreatePolicy][] request, the value is
   * ignored.
   * </pre>
   *
   * <code>string etag = 6;</code>
   *
   * @return The etag.
   */
  @java.lang.Override
  public java.lang.String getEtag() {
    return etag_;
  }
  /**
   *
   *
   * <pre>
   * An opaque tag that identifies the current version of the `Policy`. IAM uses
   * this value to help manage concurrent updates, so they do not cause one
   * update to be overwritten by another.
   *
   * If this field is present in a [CreatePolicy][] request, the value is
   * ignored.
   * </pre>
   *
   * <code>string etag = 6;</code>
   *
   * @return The bytes for etag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEtagBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(etag_);
  }
  /**
   *
   *
   * <pre>
   * An opaque tag that identifies the current version of the `Policy`. IAM uses
   * this value to help manage concurrent updates, so they do not cause one
   * update to be overwritten by another.
   *
   * If this field is present in a [CreatePolicy][] request, the value is
   * ignored.
   * </pre>
   *
   * <code>string etag = 6;</code>
   *
   * @param value The etag to set.
   */
  private void setEtag(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    etag_ = value;
  }
  /**
   *
   *
   * <pre>
   * An opaque tag that identifies the current version of the `Policy`. IAM uses
   * this value to help manage concurrent updates, so they do not cause one
   * update to be overwritten by another.
   *
   * If this field is present in a [CreatePolicy][] request, the value is
   * ignored.
   * </pre>
   *
   * <code>string etag = 6;</code>
   */
  private void clearEtag() {

    etag_ = getDefaultInstance().getEtag();
  }
  /**
   *
   *
   * <pre>
   * An opaque tag that identifies the current version of the `Policy`. IAM uses
   * this value to help manage concurrent updates, so they do not cause one
   * update to be overwritten by another.
   *
   * If this field is present in a [CreatePolicy][] request, the value is
   * ignored.
   * </pre>
   *
   * <code>string etag = 6;</code>
   *
   * @param value The bytes for etag to set.
   */
  private void setEtagBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    etag_ = value.toStringUtf8();
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp createTime_;
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  private void setCreateTime(com.google.protobuf.Timestamp value) {
    value.getClass();
    createTime_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCreateTime(com.google.protobuf.Timestamp value) {
    value.getClass();
    if (createTime_ != null && createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      createTime_ =
          com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
    } else {
      createTime_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  private void clearCreateTime() {
    createTime_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int UPDATE_TIME_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  private void setUpdateTime(com.google.protobuf.Timestamp value) {
    value.getClass();
    updateTime_ = value;
    bitField0_ |= 0x00000002;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUpdateTime(com.google.protobuf.Timestamp value) {
    value.getClass();
    if (updateTime_ != null && updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      updateTime_ =
          com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
    } else {
      updateTime_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was last updated.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  private void clearUpdateTime() {
    updateTime_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int DELETE_TIME_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp deleteTime_;
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.Override
  public boolean hasDeleteTime() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeleteTime() {
    return deleteTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deleteTime_;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  private void setDeleteTime(com.google.protobuf.Timestamp value) {
    value.getClass();
    deleteTime_ = value;
    bitField0_ |= 0x00000004;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeDeleteTime(com.google.protobuf.Timestamp value) {
    value.getClass();
    if (deleteTime_ != null && deleteTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      deleteTime_ =
          com.google.protobuf.Timestamp.newBuilder(deleteTime_).mergeFrom(value).buildPartial();
    } else {
      deleteTime_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   *
   *
   * <pre>
   * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  private void clearDeleteTime() {
    deleteTime_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int RULES_FIELD_NUMBER = 10;
  private com.google.protobuf.Internal.ProtobufList<com.google.iam.v2.PolicyRule> rules_;
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.iam.v2.PolicyRule> getRulesList() {
    return rules_;
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  public java.util.List<? extends com.google.iam.v2.PolicyRuleOrBuilder> getRulesOrBuilderList() {
    return rules_;
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  @java.lang.Override
  public int getRulesCount() {
    return rules_.size();
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  @java.lang.Override
  public com.google.iam.v2.PolicyRule getRules(int index) {
    return rules_.get(index);
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  public com.google.iam.v2.PolicyRuleOrBuilder getRulesOrBuilder(int index) {
    return rules_.get(index);
  }

  private void ensureRulesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.iam.v2.PolicyRule> tmp = rules_;
    if (!tmp.isModifiable()) {
      rules_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }

  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  private void setRules(int index, com.google.iam.v2.PolicyRule value) {
    value.getClass();
    ensureRulesIsMutable();
    rules_.set(index, value);
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  private void addRules(com.google.iam.v2.PolicyRule value) {
    value.getClass();
    ensureRulesIsMutable();
    rules_.add(value);
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  private void addRules(int index, com.google.iam.v2.PolicyRule value) {
    value.getClass();
    ensureRulesIsMutable();
    rules_.add(index, value);
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  private void addAllRules(java.lang.Iterable<? extends com.google.iam.v2.PolicyRule> values) {
    ensureRulesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(values, rules_);
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  private void clearRules() {
    rules_ = emptyProtobufList();
  }
  /**
   *
   *
   * <pre>
   * A list of rules that specify the behavior of the `Policy`. All of the rules
   * should be of the `kind` specified in the `Policy`.
   * </pre>
   *
   * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
   */
  private void removeRules(int index) {
    ensureRulesIsMutable();
    rules_.remove(index);
  }

  public static final int MANAGING_AUTHORITY_FIELD_NUMBER = 11;
  private java.lang.String managingAuthority_;
  /**
   *
   *
   * <pre>
   * Immutable. Specifies that this policy is managed by an authority and can only be
   * modified by that authority. Usage is restricted.
   * </pre>
   *
   * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @return The managingAuthority.
   */
  @java.lang.Override
  public java.lang.String getManagingAuthority() {
    return managingAuthority_;
  }
  /**
   *
   *
   * <pre>
   * Immutable. Specifies that this policy is managed by an authority and can only be
   * modified by that authority. Usage is restricted.
   * </pre>
   *
   * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @return The bytes for managingAuthority.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getManagingAuthorityBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(managingAuthority_);
  }
  /**
   *
   *
   * <pre>
   * Immutable. Specifies that this policy is managed by an authority and can only be
   * modified by that authority. Usage is restricted.
   * </pre>
   *
   * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @param value The managingAuthority to set.
   */
  private void setManagingAuthority(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    managingAuthority_ = value;
  }
  /**
   *
   *
   * <pre>
   * Immutable. Specifies that this policy is managed by an authority and can only be
   * modified by that authority. Usage is restricted.
   * </pre>
   *
   * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
   */
  private void clearManagingAuthority() {

    managingAuthority_ = getDefaultInstance().getManagingAuthority();
  }
  /**
   *
   *
   * <pre>
   * Immutable. Specifies that this policy is managed by an authority and can only be
   * modified by that authority. Usage is restricted.
   * </pre>
   *
   * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
   *
   * @param value The bytes for managingAuthority to set.
   */
  private void setManagingAuthorityBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    managingAuthority_ = value.toStringUtf8();
  }

  public static com.google.iam.v2.Policy parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.iam.v2.Policy parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.iam.v2.Policy parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.iam.v2.Policy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.iam.v2.Policy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.iam.v2.Policy parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.iam.v2.Policy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.iam.v2.Policy parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.iam.v2.Policy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.iam.v2.Policy parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.iam.v2.Policy parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.iam.v2.Policy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.google.iam.v2.Policy prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * Data for an IAM policy.
   * </pre>
   *
   * Protobuf type {@code google.iam.v2.Policy}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<com.google.iam.v2.Policy, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.iam.v2.Policy)
      com.google.iam.v2.PolicyOrBuilder {
    // Construct using com.google.iam.v2.Policy.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     *
     *
     * <pre>
     * Immutable. The resource name of the `Policy`, which must be unique. Format:
     * `policies/{attachment_point}/denypolicies/{policy_id}`
     *
     *
     * The attachment point is identified by its URL-encoded full resource name,
     * which means that the forward-slash character, `/`, must be written as
     * `%2F`. For example,
     * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
     *
     * For organizations and folders, use the numeric ID in the full resource
     * name. For projects, requests can use the alphanumeric or the numeric ID.
     * Responses always contain the numeric ID.
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     *
     *
     * <pre>
     * Immutable. The resource name of the `Policy`, which must be unique. Format:
     * `policies/{attachment_point}/denypolicies/{policy_id}`
     *
     *
     * The attachment point is identified by its URL-encoded full resource name,
     * which means that the forward-slash character, `/`, must be written as
     * `%2F`. For example,
     * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
     *
     * For organizations and folders, use the numeric ID in the full resource
     * name. For projects, requests can use the alphanumeric or the numeric ID.
     * Responses always contain the numeric ID.
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     *
     *
     * <pre>
     * Immutable. The resource name of the `Policy`, which must be unique. Format:
     * `policies/{attachment_point}/denypolicies/{policy_id}`
     *
     *
     * The attachment point is identified by its URL-encoded full resource name,
     * which means that the forward-slash character, `/`, must be written as
     * `%2F`. For example,
     * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
     *
     * For organizations and folders, use the numeric ID in the full resource
     * name. For projects, requests can use the alphanumeric or the numeric ID.
     * Responses always contain the numeric ID.
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Immutable. The resource name of the `Policy`, which must be unique. Format:
     * `policies/{attachment_point}/denypolicies/{policy_id}`
     *
     *
     * The attachment point is identified by its URL-encoded full resource name,
     * which means that the forward-slash character, `/`, must be written as
     * `%2F`. For example,
     * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
     *
     * For organizations and folders, use the numeric ID in the full resource
     * name. For projects, requests can use the alphanumeric or the numeric ID.
     * Responses always contain the numeric ID.
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Immutable. The resource name of the `Policy`, which must be unique. Format:
     * `policies/{attachment_point}/denypolicies/{policy_id}`
     *
     *
     * The attachment point is identified by its URL-encoded full resource name,
     * which means that the forward-slash character, `/`, must be written as
     * `%2F`. For example,
     * `policies/cloudresourcemanager.googleapis.com%2Fprojects%2Fmy-project/denypolicies/my-deny-policy`.
     *
     * For organizations and folders, use the numeric ID in the full resource
     * name. For projects, requests can use the alphanumeric or the numeric ID.
     * Responses always contain the numeric ID.
     * </pre>
     *
     * <code>string name = 1 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
     * `Policy` is created.
     * </pre>
     *
     * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
      return instance.getUid();
    }
    /**
     *
     *
     * <pre>
     * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
     * `Policy` is created.
     * </pre>
     *
     * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUidBytes() {
      return instance.getUidBytes();
    }
    /**
     *
     *
     * <pre>
     * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
     * `Policy` is created.
     * </pre>
     *
     * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(java.lang.String value) {
      copyOnWrite();
      instance.setUid(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
     * `Policy` is created.
     * </pre>
     *
     * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      copyOnWrite();
      instance.clearUid();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Immutable. The globally unique ID of the `Policy`. Assigned automatically when the
     * `Policy` is created.
     * </pre>
     *
     * <code>string uid = 2 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUidBytes(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
     * </pre>
     *
     * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     *
     * @return The kind.
     */
    @java.lang.Override
    public java.lang.String getKind() {
      return instance.getKind();
    }
    /**
     *
     *
     * <pre>
     * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
     * </pre>
     *
     * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     *
     * @return The bytes for kind.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKindBytes() {
      return instance.getKindBytes();
    }
    /**
     *
     *
     * <pre>
     * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
     * </pre>
     *
     * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     *
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(java.lang.String value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
     * </pre>
     *
     * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The kind of the `Policy`. Always contains the value `DenyPolicy`.
     * </pre>
     *
     * <code>string kind = 3 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     *
     * @param value The bytes for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKindBytes(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * A user-specified description of the `Policy`. This value can be up to 63
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     *
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     *
     *
     * <pre>
     * A user-specified description of the `Policy`. This value can be up to 63
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     *
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     *
     *
     * <pre>
     * A user-specified description of the `Policy`. This value can be up to 63
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     *
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A user-specified description of the `Policy`. This value can be up to 63
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A user-specified description of the `Policy`. This value can be up to 63
     * characters.
     * </pre>
     *
     * <code>string display_name = 4;</code>
     *
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    @java.lang.Override
    public int getAnnotationsCount() {
      return instance.getAnnotationsMap().size();
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    @java.lang.Override
    public boolean containsAnnotations(java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getAnnotationsMap().containsKey(key);
    }

    public Builder clearAnnotations() {
      copyOnWrite();
      instance.getMutableAnnotationsMap().clear();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    public Builder removeAnnotations(java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableAnnotationsMap().remove(key);
      return this;
    }
    /** Use {@link #getAnnotationsMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
      return getAnnotationsMap();
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
      return java.util.Collections.unmodifiableMap(instance.getAnnotationsMap());
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    @java.lang.Override
    public /* nullable */ java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        /* nullable */
        java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map = instance.getAnnotationsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    @java.lang.Override
    public java.lang.String getAnnotationsOrThrow(java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map = instance.getAnnotationsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    public Builder putAnnotations(java.lang.String key, java.lang.String value) {
      java.lang.Class<?> keyClass = key.getClass();
      java.lang.Class<?> valueClass = value.getClass();
      copyOnWrite();
      instance.getMutableAnnotationsMap().put(key, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A key-value map to store arbitrary metadata for the `Policy`. Keys
     * can be up to 63 characters. Values can be up to 255 characters.
     * </pre>
     *
     * <code>map&lt;string, string&gt; annotations = 5;</code>
     */
    public Builder putAllAnnotations(java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableAnnotationsMap().putAll(values);
      return this;
    }

    /**
     *
     *
     * <pre>
     * An opaque tag that identifies the current version of the `Policy`. IAM uses
     * this value to help manage concurrent updates, so they do not cause one
     * update to be overwritten by another.
     *
     * If this field is present in a [CreatePolicy][] request, the value is
     * ignored.
     * </pre>
     *
     * <code>string etag = 6;</code>
     *
     * @return The etag.
     */
    @java.lang.Override
    public java.lang.String getEtag() {
      return instance.getEtag();
    }
    /**
     *
     *
     * <pre>
     * An opaque tag that identifies the current version of the `Policy`. IAM uses
     * this value to help manage concurrent updates, so they do not cause one
     * update to be overwritten by another.
     *
     * If this field is present in a [CreatePolicy][] request, the value is
     * ignored.
     * </pre>
     *
     * <code>string etag = 6;</code>
     *
     * @return The bytes for etag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEtagBytes() {
      return instance.getEtagBytes();
    }
    /**
     *
     *
     * <pre>
     * An opaque tag that identifies the current version of the `Policy`. IAM uses
     * this value to help manage concurrent updates, so they do not cause one
     * update to be overwritten by another.
     *
     * If this field is present in a [CreatePolicy][] request, the value is
     * ignored.
     * </pre>
     *
     * <code>string etag = 6;</code>
     *
     * @param value The etag to set.
     * @return This builder for chaining.
     */
    public Builder setEtag(java.lang.String value) {
      copyOnWrite();
      instance.setEtag(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * An opaque tag that identifies the current version of the `Policy`. IAM uses
     * this value to help manage concurrent updates, so they do not cause one
     * update to be overwritten by another.
     *
     * If this field is present in a [CreatePolicy][] request, the value is
     * ignored.
     * </pre>
     *
     * <code>string etag = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearEtag() {
      copyOnWrite();
      instance.clearEtag();
      return this;
    }
    /**
     *
     *
     * <pre>
     * An opaque tag that identifies the current version of the `Policy`. IAM uses
     * this value to help manage concurrent updates, so they do not cause one
     * update to be overwritten by another.
     *
     * If this field is present in a [CreatePolicy][] request, the value is
     * ignored.
     * </pre>
     *
     * <code>string etag = 6;</code>
     *
     * @param value The bytes for etag to set.
     * @return This builder for chaining.
     */
    public Builder setEtagBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEtagBytes(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was created.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    @java.lang.Override
    public boolean hasCreateTime() {
      return instance.hasCreateTime();
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was created.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreateTime() {
      return instance.getCreateTime();
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was created.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setCreateTime(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was created.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setCreateTime(builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was created.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeCreateTime(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was created.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp create_time = 7 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder clearCreateTime() {
      copyOnWrite();
      instance.clearCreateTime();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was last updated.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    @java.lang.Override
    public boolean hasUpdateTime() {
      return instance.hasUpdateTime();
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was last updated.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdateTime() {
      return instance.getUpdateTime();
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was last updated.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setUpdateTime(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was last updated.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdateTime(builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was last updated.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeUpdateTime(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was last updated.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp update_time = 8 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder clearUpdateTime() {
      copyOnWrite();
      instance.clearUpdateTime();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    @java.lang.Override
    public boolean hasDeleteTime() {
      return instance.hasDeleteTime();
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDeleteTime() {
      return instance.getDeleteTime();
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder setDeleteTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setDeleteTime(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder setDeleteTime(com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setDeleteTime(builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder mergeDeleteTime(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeDeleteTime(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Output only. The time when the `Policy` was deleted. Empty if the policy is not deleted.
     * </pre>
     *
     * <code>
     * .google.protobuf.Timestamp delete_time = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     */
    public Builder clearDeleteTime() {
      copyOnWrite();
      instance.clearDeleteTime();
      return this;
    }

    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.iam.v2.PolicyRule> getRulesList() {
      return java.util.Collections.unmodifiableList(instance.getRulesList());
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    @java.lang.Override
    public int getRulesCount() {
      return instance.getRulesCount();
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */

    @java.lang.Override
    public com.google.iam.v2.PolicyRule getRules(int index) {
      return instance.getRules(index);
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder setRules(int index, com.google.iam.v2.PolicyRule value) {
      copyOnWrite();
      instance.setRules(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder setRules(int index, com.google.iam.v2.PolicyRule.Builder builderForValue) {
      copyOnWrite();
      instance.setRules(index, builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder addRules(com.google.iam.v2.PolicyRule value) {
      copyOnWrite();
      instance.addRules(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder addRules(int index, com.google.iam.v2.PolicyRule value) {
      copyOnWrite();
      instance.addRules(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder addRules(com.google.iam.v2.PolicyRule.Builder builderForValue) {
      copyOnWrite();
      instance.addRules(builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder addRules(int index, com.google.iam.v2.PolicyRule.Builder builderForValue) {
      copyOnWrite();
      instance.addRules(index, builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder addAllRules(java.lang.Iterable<? extends com.google.iam.v2.PolicyRule> values) {
      copyOnWrite();
      instance.addAllRules(values);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder clearRules() {
      copyOnWrite();
      instance.clearRules();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of rules that specify the behavior of the `Policy`. All of the rules
     * should be of the `kind` specified in the `Policy`.
     * </pre>
     *
     * <code>repeated .google.iam.v2.PolicyRule rules = 10;</code>
     */
    public Builder removeRules(int index) {
      copyOnWrite();
      instance.removeRules(index);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Immutable. Specifies that this policy is managed by an authority and can only be
     * modified by that authority. Usage is restricted.
     * </pre>
     *
     * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return The managingAuthority.
     */
    @java.lang.Override
    public java.lang.String getManagingAuthority() {
      return instance.getManagingAuthority();
    }
    /**
     *
     *
     * <pre>
     * Immutable. Specifies that this policy is managed by an authority and can only be
     * modified by that authority. Usage is restricted.
     * </pre>
     *
     * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return The bytes for managingAuthority.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getManagingAuthorityBytes() {
      return instance.getManagingAuthorityBytes();
    }
    /**
     *
     *
     * <pre>
     * Immutable. Specifies that this policy is managed by an authority and can only be
     * modified by that authority. Usage is restricted.
     * </pre>
     *
     * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @param value The managingAuthority to set.
     * @return This builder for chaining.
     */
    public Builder setManagingAuthority(java.lang.String value) {
      copyOnWrite();
      instance.setManagingAuthority(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Immutable. Specifies that this policy is managed by an authority and can only be
     * modified by that authority. Usage is restricted.
     * </pre>
     *
     * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearManagingAuthority() {
      copyOnWrite();
      instance.clearManagingAuthority();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Immutable. Specifies that this policy is managed by an authority and can only be
     * modified by that authority. Usage is restricted.
     * </pre>
     *
     * <code>string managing_authority = 11 [(.google.api.field_behavior) = IMMUTABLE];</code>
     *
     * @param value The bytes for managingAuthority to set.
     * @return This builder for chaining.
     */
    public Builder setManagingAuthorityBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setManagingAuthorityBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.iam.v2.Policy)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.google.iam.v2.Policy();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "bitField0_",
                "name_",
                "uid_",
                "kind_",
                "displayName_",
                "annotations_",
                AnnotationsDefaultEntryHolder.defaultEntry,
                "etag_",
                "createTime_",
                "updateTime_",
                "deleteTime_",
                "rules_",
                com.google.iam.v2.PolicyRule.class,
                "managingAuthority_",
              };
          java.lang.String info =
              "\u0000\u000b\u0000\u0001\u0001\u000b\u000b\u0001\u0001\u0000\u0001\u0208\u0002\u0208"
                  + "\u0003\u0208\u0004\u0208\u00052\u0006\u0208\u0007\u1009\u0000\b\u1009\u0001\t\u1009"
                  + "\u0002\n\u001b\u000b\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.google.iam.v2.Policy> parser = PARSER;
          if (parser == null) {
            synchronized (com.google.iam.v2.Policy.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser<com.google.iam.v2.Policy>(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:google.iam.v2.Policy)
  private static final com.google.iam.v2.Policy DEFAULT_INSTANCE;

  static {
    Policy defaultInstance = new Policy();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(Policy.class, defaultInstance);
  }

  public static com.google.iam.v2.Policy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Policy> PARSER;

  public static com.google.protobuf.Parser<Policy> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
