/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/rpc/error_details.proto

// Protobuf Java Version: 3.25.5
package com.google.rpc;

/**
 *
 *
 * <pre>
 * Describes additional debugging info.
 * </pre>
 *
 * Protobuf type {@code google.rpc.DebugInfo}
 */
public final class DebugInfo
    extends com.google.protobuf.GeneratedMessageLite<DebugInfo, DebugInfo.Builder>
    implements
    // @@protoc_insertion_point(message_implements:google.rpc.DebugInfo)
    DebugInfoOrBuilder {
  private DebugInfo() {
    stackEntries_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    detail_ = "";
  }

  public static final int STACK_ENTRIES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> stackEntries_;
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @return A list containing the stackEntries.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getStackEntriesList() {
    return stackEntries_;
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @return The count of stackEntries.
   */
  @java.lang.Override
  public int getStackEntriesCount() {
    return stackEntries_.size();
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @param index The index of the element to return.
   * @return The stackEntries at the given index.
   */
  @java.lang.Override
  public java.lang.String getStackEntries(int index) {
    return stackEntries_.get(index);
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the stackEntries at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStackEntriesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(stackEntries_.get(index));
  }

  private void ensureStackEntriesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp = stackEntries_;
    if (!tmp.isModifiable()) {
      stackEntries_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @param index The index to set the value at.
   * @param value The stackEntries to set.
   */
  private void setStackEntries(int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
    ensureStackEntriesIsMutable();
    stackEntries_.set(index, value);
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @param value The stackEntries to add.
   */
  private void addStackEntries(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
    ensureStackEntriesIsMutable();
    stackEntries_.add(value);
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @param values The stackEntries to add.
   */
  private void addAllStackEntries(java.lang.Iterable<java.lang.String> values) {
    ensureStackEntriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(values, stackEntries_);
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   */
  private void clearStackEntries() {
    stackEntries_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   *
   *
   * <pre>
   * The stack trace entries indicating where the error occurred.
   * </pre>
   *
   * <code>repeated string stack_entries = 1;</code>
   *
   * @param value The bytes of the stackEntries to add.
   */
  private void addStackEntriesBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureStackEntriesIsMutable();
    stackEntries_.add(value.toStringUtf8());
  }

  public static final int DETAIL_FIELD_NUMBER = 2;
  private java.lang.String detail_;
  /**
   *
   *
   * <pre>
   * Additional debugging information provided by the server.
   * </pre>
   *
   * <code>string detail = 2;</code>
   *
   * @return The detail.
   */
  @java.lang.Override
  public java.lang.String getDetail() {
    return detail_;
  }
  /**
   *
   *
   * <pre>
   * Additional debugging information provided by the server.
   * </pre>
   *
   * <code>string detail = 2;</code>
   *
   * @return The bytes for detail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDetailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(detail_);
  }
  /**
   *
   *
   * <pre>
   * Additional debugging information provided by the server.
   * </pre>
   *
   * <code>string detail = 2;</code>
   *
   * @param value The detail to set.
   */
  private void setDetail(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    detail_ = value;
  }
  /**
   *
   *
   * <pre>
   * Additional debugging information provided by the server.
   * </pre>
   *
   * <code>string detail = 2;</code>
   */
  private void clearDetail() {

    detail_ = getDefaultInstance().getDetail();
  }
  /**
   *
   *
   * <pre>
   * Additional debugging information provided by the server.
   * </pre>
   *
   * <code>string detail = 2;</code>
   *
   * @param value The bytes for detail to set.
   */
  private void setDetailBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    detail_ = value.toStringUtf8();
  }

  public static com.google.rpc.DebugInfo parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.rpc.DebugInfo parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.rpc.DebugInfo parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.rpc.DebugInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.rpc.DebugInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.rpc.DebugInfo parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.rpc.DebugInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.rpc.DebugInfo parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.rpc.DebugInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.rpc.DebugInfo parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.rpc.DebugInfo parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.rpc.DebugInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.google.rpc.DebugInfo prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * Describes additional debugging info.
   * </pre>
   *
   * Protobuf type {@code google.rpc.DebugInfo}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<com.google.rpc.DebugInfo, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.rpc.DebugInfo)
      com.google.rpc.DebugInfoOrBuilder {
    // Construct using com.google.rpc.DebugInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @return A list containing the stackEntries.
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getStackEntriesList() {
      return java.util.Collections.unmodifiableList(instance.getStackEntriesList());
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @return The count of stackEntries.
     */
    @java.lang.Override
    public int getStackEntriesCount() {
      return instance.getStackEntriesCount();
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The stackEntries at the given index.
     */
    @java.lang.Override
    public java.lang.String getStackEntries(int index) {
      return instance.getStackEntries(index);
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the stackEntries at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStackEntriesBytes(int index) {
      return instance.getStackEntriesBytes(index);
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @param index The index to set the value at.
     * @param value The stackEntries to set.
     * @return This builder for chaining.
     */
    public Builder setStackEntries(int index, java.lang.String value) {
      copyOnWrite();
      instance.setStackEntries(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @param value The stackEntries to add.
     * @return This builder for chaining.
     */
    public Builder addStackEntries(java.lang.String value) {
      copyOnWrite();
      instance.addStackEntries(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @param values The stackEntries to add.
     * @return This builder for chaining.
     */
    public Builder addAllStackEntries(java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllStackEntries(values);
      return this;
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearStackEntries() {
      copyOnWrite();
      instance.clearStackEntries();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The stack trace entries indicating where the error occurred.
     * </pre>
     *
     * <code>repeated string stack_entries = 1;</code>
     *
     * @param value The bytes of the stackEntries to add.
     * @return This builder for chaining.
     */
    public Builder addStackEntriesBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addStackEntriesBytes(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Additional debugging information provided by the server.
     * </pre>
     *
     * <code>string detail = 2;</code>
     *
     * @return The detail.
     */
    @java.lang.Override
    public java.lang.String getDetail() {
      return instance.getDetail();
    }
    /**
     *
     *
     * <pre>
     * Additional debugging information provided by the server.
     * </pre>
     *
     * <code>string detail = 2;</code>
     *
     * @return The bytes for detail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDetailBytes() {
      return instance.getDetailBytes();
    }
    /**
     *
     *
     * <pre>
     * Additional debugging information provided by the server.
     * </pre>
     *
     * <code>string detail = 2;</code>
     *
     * @param value The detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetail(java.lang.String value) {
      copyOnWrite();
      instance.setDetail(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * Additional debugging information provided by the server.
     * </pre>
     *
     * <code>string detail = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDetail() {
      copyOnWrite();
      instance.clearDetail();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Additional debugging information provided by the server.
     * </pre>
     *
     * <code>string detail = 2;</code>
     *
     * @param value The bytes for detail to set.
     * @return This builder for chaining.
     */
    public Builder setDetailBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDetailBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.rpc.DebugInfo)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.google.rpc.DebugInfo();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "stackEntries_", "detail_",
              };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u021a\u0002\u0208"
                  + "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.google.rpc.DebugInfo> parser = PARSER;
          if (parser == null) {
            synchronized (com.google.rpc.DebugInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser<com.google.rpc.DebugInfo>(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:google.rpc.DebugInfo)
  private static final com.google.rpc.DebugInfo DEFAULT_INSTANCE;

  static {
    DebugInfo defaultInstance = new DebugInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DebugInfo.class, defaultInstance);
  }

  public static com.google.rpc.DebugInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugInfo> PARSER;

  public static com.google.protobuf.Parser<DebugInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
