// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iam/v2beta/policy.proto

package com.google.iam.v2beta;

public interface PolicyOperationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.iam.v2beta.PolicyOperationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Timestamp when the `google.longrunning.Operation` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 1;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   * Timestamp when the `google.longrunning.Operation` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 1;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   * Timestamp when the `google.longrunning.Operation` was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp create_time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();
}
