// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/google/showcase/v1beta1/sequence.proto

package com.google.showcase.v1beta1;

public interface AttemptStreamingSequenceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.showcase.v1beta1.AttemptStreamingSequenceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The content specified in the request.
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * The content specified in the request.
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
