// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/google/showcase/v1beta1/echo.proto

// Protobuf Java Version: 3.25.0
package com.google.showcase.v1beta1;

public interface BlockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.showcase.v1beta1.BlockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This content can contain anything, the server will not depend on a value
   * here.
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * This content can contain anything, the server will not depend on a value
   * here.
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
