// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/google/showcase/v1beta1/messaging.proto

// Protobuf Java Version: 3.25.1
package com.google.showcase.v1beta1;

public interface CreateRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.showcase.v1beta1.CreateRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The room to create.
   * </pre>
   *
   * <code>.google.showcase.v1beta1.Room room = 1;</code>
   * @return Whether the room field is set.
   */
  boolean hasRoom();
  /**
   * <pre>
   * The room to create.
   * </pre>
   *
   * <code>.google.showcase.v1beta1.Room room = 1;</code>
   * @return The room.
   */
  com.google.showcase.v1beta1.Room getRoom();
  /**
   * <pre>
   * The room to create.
   * </pre>
   *
   * <code>.google.showcase.v1beta1.Room room = 1;</code>
   */
  com.google.showcase.v1beta1.RoomOrBuilder getRoomOrBuilder();
}
