/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/iam/v1/resource_policy_member.proto

// Protobuf Java Version: 3.25.5
package com.google.iam.v1;

/**
 *
 *
 * <pre>
 * Output-only policy member strings of a Google Cloud resource's built-in
 * identity.
 * </pre>
 *
 * Protobuf type {@code google.iam.v1.ResourcePolicyMember}
 */
public final class ResourcePolicyMember
    extends com.google.protobuf.GeneratedMessageLite<
        ResourcePolicyMember, ResourcePolicyMember.Builder>
    implements
    // @@protoc_insertion_point(message_implements:google.iam.v1.ResourcePolicyMember)
    ResourcePolicyMemberOrBuilder {
  private ResourcePolicyMember() {
    iamPolicyNamePrincipal_ = "";
    iamPolicyUidPrincipal_ = "";
  }

  public static final int IAM_POLICY_NAME_PRINCIPAL_FIELD_NUMBER = 1;
  private java.lang.String iamPolicyNamePrincipal_;
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * user-assigned name (https://google.aip.dev/122). If a resource is deleted
   * and recreated with the same name, the binding will be applicable to the new
   * resource.
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
   * </pre>
   *
   * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The iamPolicyNamePrincipal.
   */
  @java.lang.Override
  public java.lang.String getIamPolicyNamePrincipal() {
    return iamPolicyNamePrincipal_;
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * user-assigned name (https://google.aip.dev/122). If a resource is deleted
   * and recreated with the same name, the binding will be applicable to the new
   * resource.
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
   * </pre>
   *
   * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The bytes for iamPolicyNamePrincipal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIamPolicyNamePrincipalBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(iamPolicyNamePrincipal_);
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * user-assigned name (https://google.aip.dev/122). If a resource is deleted
   * and recreated with the same name, the binding will be applicable to the new
   * resource.
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
   * </pre>
   *
   * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @param value The iamPolicyNamePrincipal to set.
   */
  private void setIamPolicyNamePrincipal(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    iamPolicyNamePrincipal_ = value;
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * user-assigned name (https://google.aip.dev/122). If a resource is deleted
   * and recreated with the same name, the binding will be applicable to the new
   * resource.
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
   * </pre>
   *
   * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  private void clearIamPolicyNamePrincipal() {

    iamPolicyNamePrincipal_ = getDefaultInstance().getIamPolicyNamePrincipal();
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * user-assigned name (https://google.aip.dev/122). If a resource is deleted
   * and recreated with the same name, the binding will be applicable to the new
   * resource.
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
   * </pre>
   *
   * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @param value The bytes for iamPolicyNamePrincipal to set.
   */
  private void setIamPolicyNamePrincipalBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    iamPolicyNamePrincipal_ = value.toStringUtf8();
  }

  public static final int IAM_POLICY_UID_PRINCIPAL_FIELD_NUMBER = 2;
  private java.lang.String iamPolicyUidPrincipal_;
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
   * resource is deleted and recreated with the same name, the binding will not
   * be applicable to the new resource
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
   * </pre>
   *
   * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The iamPolicyUidPrincipal.
   */
  @java.lang.Override
  public java.lang.String getIamPolicyUidPrincipal() {
    return iamPolicyUidPrincipal_;
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
   * resource is deleted and recreated with the same name, the binding will not
   * be applicable to the new resource
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
   * </pre>
   *
   * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The bytes for iamPolicyUidPrincipal.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getIamPolicyUidPrincipalBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(iamPolicyUidPrincipal_);
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
   * resource is deleted and recreated with the same name, the binding will not
   * be applicable to the new resource
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
   * </pre>
   *
   * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @param value The iamPolicyUidPrincipal to set.
   */
  private void setIamPolicyUidPrincipal(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    iamPolicyUidPrincipal_ = value;
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
   * resource is deleted and recreated with the same name, the binding will not
   * be applicable to the new resource
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
   * </pre>
   *
   * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  private void clearIamPolicyUidPrincipal() {

    iamPolicyUidPrincipal_ = getDefaultInstance().getIamPolicyUidPrincipal();
  }
  /**
   *
   *
   * <pre>
   * IAM policy binding member referring to a Google Cloud resource by
   * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
   * resource is deleted and recreated with the same name, the binding will not
   * be applicable to the new resource
   *
   * Example:
   * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
   * </pre>
   *
   * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @param value The bytes for iamPolicyUidPrincipal to set.
   */
  private void setIamPolicyUidPrincipalBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    iamPolicyUidPrincipal_ = value.toStringUtf8();
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.iam.v1.ResourcePolicyMember parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.google.iam.v1.ResourcePolicyMember prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * Output-only policy member strings of a Google Cloud resource's built-in
   * identity.
   * </pre>
   *
   * Protobuf type {@code google.iam.v1.ResourcePolicyMember}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.iam.v1.ResourcePolicyMember, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.iam.v1.ResourcePolicyMember)
      com.google.iam.v1.ResourcePolicyMemberOrBuilder {
    // Construct using com.google.iam.v1.ResourcePolicyMember.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * user-assigned name (https://google.aip.dev/122). If a resource is deleted
     * and recreated with the same name, the binding will be applicable to the new
     * resource.
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
     * </pre>
     *
     * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @return The iamPolicyNamePrincipal.
     */
    @java.lang.Override
    public java.lang.String getIamPolicyNamePrincipal() {
      return instance.getIamPolicyNamePrincipal();
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * user-assigned name (https://google.aip.dev/122). If a resource is deleted
     * and recreated with the same name, the binding will be applicable to the new
     * resource.
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
     * </pre>
     *
     * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @return The bytes for iamPolicyNamePrincipal.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIamPolicyNamePrincipalBytes() {
      return instance.getIamPolicyNamePrincipalBytes();
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * user-assigned name (https://google.aip.dev/122). If a resource is deleted
     * and recreated with the same name, the binding will be applicable to the new
     * resource.
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
     * </pre>
     *
     * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @param value The iamPolicyNamePrincipal to set.
     * @return This builder for chaining.
     */
    public Builder setIamPolicyNamePrincipal(java.lang.String value) {
      copyOnWrite();
      instance.setIamPolicyNamePrincipal(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * user-assigned name (https://google.aip.dev/122). If a resource is deleted
     * and recreated with the same name, the binding will be applicable to the new
     * resource.
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
     * </pre>
     *
     * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearIamPolicyNamePrincipal() {
      copyOnWrite();
      instance.clearIamPolicyNamePrincipal();
      return this;
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * user-assigned name (https://google.aip.dev/122). If a resource is deleted
     * and recreated with the same name, the binding will be applicable to the new
     * resource.
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/name/locations/us-central1-a/parameters/my-parameter`
     * </pre>
     *
     * <code>string iam_policy_name_principal = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @param value The bytes for iamPolicyNamePrincipal to set.
     * @return This builder for chaining.
     */
    public Builder setIamPolicyNamePrincipalBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIamPolicyNamePrincipalBytes(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
     * resource is deleted and recreated with the same name, the binding will not
     * be applicable to the new resource
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
     * </pre>
     *
     * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @return The iamPolicyUidPrincipal.
     */
    @java.lang.Override
    public java.lang.String getIamPolicyUidPrincipal() {
      return instance.getIamPolicyUidPrincipal();
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
     * resource is deleted and recreated with the same name, the binding will not
     * be applicable to the new resource
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
     * </pre>
     *
     * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @return The bytes for iamPolicyUidPrincipal.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIamPolicyUidPrincipalBytes() {
      return instance.getIamPolicyUidPrincipalBytes();
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
     * resource is deleted and recreated with the same name, the binding will not
     * be applicable to the new resource
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
     * </pre>
     *
     * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @param value The iamPolicyUidPrincipal to set.
     * @return This builder for chaining.
     */
    public Builder setIamPolicyUidPrincipal(java.lang.String value) {
      copyOnWrite();
      instance.setIamPolicyUidPrincipal(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
     * resource is deleted and recreated with the same name, the binding will not
     * be applicable to the new resource
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
     * </pre>
     *
     * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearIamPolicyUidPrincipal() {
      copyOnWrite();
      instance.clearIamPolicyUidPrincipal();
      return this;
    }
    /**
     *
     *
     * <pre>
     * IAM policy binding member referring to a Google Cloud resource by
     * system-assigned unique identifier (https://google.aip.dev/148#uid). If a
     * resource is deleted and recreated with the same name, the binding will not
     * be applicable to the new resource
     *
     * Example:
     * `principal://parametermanager.googleapis.com/projects/12345/uid/locations/us-central1-a/parameters/a918fed5`
     * </pre>
     *
     * <code>string iam_policy_uid_principal = 2 [(.google.api.field_behavior) = OUTPUT_ONLY];
     * </code>
     *
     * @param value The bytes for iamPolicyUidPrincipal to set.
     * @return This builder for chaining.
     */
    public Builder setIamPolicyUidPrincipalBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIamPolicyUidPrincipalBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.iam.v1.ResourcePolicyMember)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.google.iam.v1.ResourcePolicyMember();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "iamPolicyNamePrincipal_", "iamPolicyUidPrincipal_",
              };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208"
                  + "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.google.iam.v1.ResourcePolicyMember> parser = PARSER;
          if (parser == null) {
            synchronized (com.google.iam.v1.ResourcePolicyMember.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.google.iam.v1.ResourcePolicyMember>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:google.iam.v1.ResourcePolicyMember)
  private static final com.google.iam.v1.ResourcePolicyMember DEFAULT_INSTANCE;

  static {
    ResourcePolicyMember defaultInstance = new ResourcePolicyMember();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ResourcePolicyMember.class, defaultInstance);
  }

  public static com.google.iam.v1.ResourcePolicyMember getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ResourcePolicyMember> PARSER;

  public static com.google.protobuf.Parser<ResourcePolicyMember> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
