# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
- "/showcase/grpc-google-.*/src"
- "/showcase/proto-google-.*/src"
- "/showcase/gapic-showcase/src"
- "/showcase/samples/snippets/generated"

deep-preserve-regex:
- "/showcase/gapic-showcase/src/test/*"

deep-copy-regex:
- source: "/schema/google/showcase/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/showcase/$1/proto-gapic-showcase-$1/src"
- source: "/schema/google/showcase/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/showcase/$1/grpc-gapic-showcase-$1/src"
- source: "/schema/google/showcase/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/showcase/$1/gapic-showcase/src"
- source: "/schema/google/showcase/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/showcase/$1/samples/snippets/generated"

api-name: showcase