# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2 hours
substitutions:
  _TEST_IMAGE_ID: "test-image:latest"
  _VERSION_CODENAME: "bookworm"
steps:
- name: gcr.io/cloud-builders/docker
  args: [
    "build",
    "-t",
    "${_TEST_IMAGE_ID}",
    "--file",
    ".cloudbuild/library_generation/library_generation.Dockerfile",
    "."
  ]
  env:
  - "DOCKER_BUILDKIT=1"
  id: library-generation-build
  waitFor: ["-"]

- name: ubuntu:25.04
  entrypoint: bash
  args:
    - "-c"
    - |
      # Install docker, see https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
      sudo apt-get update
      sudo apt-get install ca-certificates curl
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${_VERSION_CODENAME}") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update
      sudo apt-get install \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
        maven python
      # Install python dependencies
      pip install --upgrade pip
      pip install --require-hashes -r hermetic_build/common/requirements.txt
      pip install hermetic_build/common
      pip install --require-hashes -r hermetic_build/library_generation/requirements.txt
      pip install hermetic_build/library_generation
      python -m unittest hermetic_build/library_generation/tests/integration_tests.py
  waitFor: ["library-generation-build"]
  id: integration-test

options:
  logging: CLOUD_LOGGING_ONLY
