# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2 hours
substitutions:
    _TEST_IMAGE: "test-image:latest"
steps:
- name: gcr.io/cloud-builders/docker
  args: [
      "build",
      "--no-cache",
      "--build-arg", "PROTOC_VERSION=33.2",
      "-t", "${_TEST_IMAGE}",
      "-f", ".cloudbuild/library_generation/library_generation_airlock.Dockerfile",
      "."
  ]
  id: build-image
  waitFor: ["-"]
  env:
  - "DOCKER_BUILDKIT=1"

- name: alpine/git:latest
  entrypoint: /bin/sh
  args:
  - "-c"
  - |
    cd /workspace
    git clone https://github.com/googleapis/googleapis
    cd googleapis
    git checkout 113a378d5aad5018876ec0a8cbfd4d6a4f746809
  id: download-api-definitions
  waitFor: ["-"]

- name: alpine/git:latest
  entrypoint: /bin/sh
  args:
  - "-c"
  - |
    cd /workspace
    git clone https://github.com/googleapis/google-cloud-java
    cd google-cloud-java
    git checkout chore/test-hermetic-build
    mkdir ../golden
    cd ../golden
    cp -r ../google-cloud-java/java-apigee-connect .
    cp -r ../google-cloud-java/java-alloydb .
    cp -r ../google-cloud-java/java-alloydb-connectors .
    cp -r ../google-cloud-java/java-cloudcontrolspartner .
    cp -r ../google-cloud-java/gapic-libraries-bom .
    cp -r ../google-cloud-java/pom.xml .
  id: prepare-golden
  waitFor: ["-"]

- name: maven:3.9.9-eclipse-temurin-11-alpine
  entrypoint: /bin/sh
  args:
  - "-c"
  - |
    mvn dependency:copy \
      -B -ntp \
      -Dartifact=com.google.api:gapic-generator-java:2.63.0 \
      -DoutputDirectory=/workspace
    cd /workspace
    mv gapic-generator-java-2.63.0.jar gapic-generator-java.jar
  id: prepare-generator-jar
  waitFor: [ "-" ]

- name: gcr.io/cloud-builders/docker
  args: [
    "run",
    "--rm",
    "-v", "/workspace/google-cloud-java:/workspace",
    "-v", "/workspace/hermetic_build/library_generation/tests/resources/integration/google-cloud-java:/workspace/config",
    "-v", "/workspace/googleapis:/workspace/apis",
    # Fix gapic-generator-java so that the generation result stays
    # the same.
    "-v", "/workspace/gapic-generator-java.jar:/home/.library_generation/gapic-generator-java.jar",
    "${_TEST_IMAGE}",
    "--generation-config-path=/workspace/config/generation_config.yaml",
    "--api-definitions-path=/workspace/apis"
  ]
  env:
  - "DOCKER_BUILDKIT=1"
  id: generate-libraries
  waitFor: [
    "build-image",
    "download-api-definitions",
    "prepare-golden",
    "prepare-generator-jar"
  ]

- name: python:3.12.7-alpine3.20
  entrypoint: /bin/sh
  args:
  - "-c"
  - |
    python3 -m venv .venv
    source .venv/bin/activate
    pip install --require-hashes -r requirements.txt
    python -m unittest integration_tests.py
  dir: ".cloudbuild/library_generation/scripts"
  id: verify-generation
  waitFor: ["generate-libraries"]
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
