# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2 hours
substitutions:
  _TEST_IMAGE_ID: "test-image:latest"
steps:
#- name: gcr.io/cloud-builders/docker
#  args: [
#    "build",
#    "-t",
#    "${_TEST_IMAGE_ID}",
#    "--file",
#    ".cloudbuild/library_generation/library_generation.Dockerfile",
#    "."
#  ]
#  env:
#  - "DOCKER_BUILDKIT=1"
#  id: library-generation-build
#  waitFor: ["-"]

- name: ubuntu:24.04
  entrypoint: bash
  args:
    - "-c"
    - |
      # Install docker
      apt-get update
      apt-get install -y ca-certificates curl gnupg lsb-release
      mkdir -p /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get -y install \
        docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
        maven python3-virtualenv
      # Install python dependencies
      python3 -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
      pip install --require-hashes -r hermetic_build/common/requirements.txt
      pip install hermetic_build/common
      pip install --require-hashes -r hermetic_build/library_generation/requirements.txt
      pip install hermetic_build/library_generation
      python3 -m unittest hermetic_build/library_generation/tests/integration_tests.py
  waitFor: ["-"]
  id: integration-test

options:
  logging: CLOUD_LOGGING_ONLY
