// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/field_behavior.proto

package com.google.api;

public final class FieldBehaviorProto {
  private FieldBehaviorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(FieldBehaviorProto.fieldBehavior);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int FIELD_BEHAVIOR_FIELD_NUMBER = 1052;
  /**
   * <pre>
   * A designation of a specific field behavior (required, output only, etc.)
   * in protobuf messages.
   * Examples:
   *   string name = 1 [(google.api.field_behavior) = REQUIRED];
   *   State state = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
   *   google.protobuf.Duration ttl = 1
   *     [(google.api.field_behavior) = INPUT_ONLY];
   *   google.protobuf.Timestamp expire_time = 1
   *     [(google.api.field_behavior) = OUTPUT_ONLY,
   *      (google.api.field_behavior) = IMMUTABLE];
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.util.List<FieldBehavior>> fieldBehavior = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        FieldBehavior.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037google/api/field_behavior.proto\022\ngoogl" +
      "e.api\032 google/protobuf/descriptor.proto*" +
      "{\n\rFieldBehavior\022\036\n\032FIELD_BEHAVIOR_UNSPE" +
      "CIFIED\020\000\022\014\n\010OPTIONAL\020\001\022\014\n\010REQUIRED\020\002\022\017\n\013" +
      "OUTPUT_ONLY\020\003\022\016\n\nINPUT_ONLY\020\004\022\r\n\tIMMUTAB" +
      "LE\020\005:Q\n\016field_behavior\022\035.google.protobuf" +
      ".FieldOptions\030\234\010 \003(\0162\031.google.api.FieldB" +
      "ehaviorBp\n\016com.google.apiB\022FieldBehavior" +
      "ProtoP\001ZAgoogle.golang.org/genproto/goog" +
      "leapis/api/annotations;annotations\242\002\004GAP" +
      "Ib\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    fieldBehavior.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
