/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/field_info.proto

// Protobuf Java Version: 3.25.5
package com.google.api;

public final class FieldInfoProto {
  private FieldInfoProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.api.FieldInfoProto.fieldInfo);
  }

  public static final int FIELD_INFO_FIELD_NUMBER = 291403980;
  /**
   *
   *
   * <pre>
   * Rich semantic descriptor of an API field beyond the basic typing.
   *
   * Examples:
   *
   *     string request_id = 1 [(google.api.field_info).format = UUID4];
   *     string old_ip_address = 2 [(google.api.field_info).format = IPV4];
   *     string new_ip_address = 3 [(google.api.field_info).format = IPV6];
   *     string actual_ip_address = 4 [
   *       (google.api.field_info).format = IPV4_OR_IPV6
   *     ];
   *     google.protobuf.Any generic_field = 5 [
   *       (google.api.field_info).referenced_types = {type_name: "ActualType"},
   *       (google.api.field_info).referenced_types = {type_name: "OtherType"},
   *     ];
   *     google.protobuf.Any generic_user_input = 5 [
   *       (google.api.field_info).referenced_types = {type_name: "*"},
   *     ];
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
          com.google.protobuf.DescriptorProtos.FieldOptions, com.google.api.FieldInfo>
      fieldInfo =
          com.google.protobuf.GeneratedMessageLite.newSingularGeneratedExtension(
              com.google.protobuf.DescriptorProtos.FieldOptions.getDefaultInstance(),
              com.google.api.FieldInfo.getDefaultInstance(),
              com.google.api.FieldInfo.getDefaultInstance(),
              null,
              291403980,
              com.google.protobuf.WireFormat.FieldType.MESSAGE,
              com.google.api.FieldInfo.class);

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
