  name: "Unmanaged dependency check"
  description: "Checks whether there's a dependency that is not managed by java shared dependencies."
  inputs:
    bom-path:
      description: "The relative path from the repository root to the pom.xml file"
      required: true
  runs:
    using: "composite"
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
    - name: Install check
      shell: bash
      run: mvn clean install --batch-mode --no-transfer-progress -DskipTests
      working-directory: java-shared-dependencies/unmanaged-dependency-check
    - name: Run unmanaged dependency check
      shell: bash
      run: |
        mvn exec:java -Dexec.args="3.20.0 ${{ inputs.bom-path }}"
        unmanaged_dependencies=$(mvn exec:java -Dexec.args="3.20.0 ${{ inputs.bom-path }}" -q)
        if [[ "${unmanaged_dependencies}" != "[]" ]]; then
          echo "Unmanaged dependencies, ${unmanaged_dependencies}, found in ${{ inputs.bom-path }}."
          echo "Please follow go/add-dependency-to-cloud-sdk-java to add a third-party dependency."
          exit 1
        fi
      working-directory: java-shared-dependencies/unmanaged-dependency-check

