name: Copy library generation script
description: Copy library generation shell script to the calling workflow

runs:
  using: "composite"
  steps:
  - name: Copy shell script
    shell: bash
    run: |
      cd ${{ github.action_path }}
      cp scripts/hermetic_library_generation.sh $GITHUB_WORKSPACE
