#!/usr/bin/env bash

set -e

working_directory=$(dirname "$(readlink -f "$0")")

exec java -classpath "$working_directory/gapic-generator-java-$gapic_generator_version.jar" com.google.api.generator.Main