#!/bin/bash
# convenience script to test locally - remove when ready for merge

GOOGLEAPIS_COMMIT=82c0f26dae2343cd1a39084283c169bf3415c950
PROTOBUF_VERSION=23.2
GRPC_VERSION=1.56.1
GAPIC_GENERATOR_VERSION=2.24.0
PROTO_PATH=google/cloud/language/v1
CONTAINS_CLOUD=true
TRANSPORT=grpc+rest
REST_NUMERIC_ENUMS=true
IS_GAPIC_LIBRARY=true
INCLUDE_SAMPLES=true
DESTINATION_PATH="null"
OWLBOT_SHA=a57d2ea6d1a77aa96c17ad0850b779ec6295f88b6c1da3d214b2095d140a2066
OWLBOT_PY_PATH="null"
REPO_METADATA_PATH=/usr/local/google/home/diegomarquezp/Desktop/google-cloud-java/java-language/.repo-metadata.json

bash generate_library.sh \
$GOOGLEAPIS_COMMIT \
$PROTOBUF_VERSION \
$GRPC_VERSION \
$GAPIC_GENERATOR_VERSION \
$PROTO_PATH \
$CONTAINS_CLOUD \
$TRANSPORT \
$REST_NUMERIC_ENUMS \
$IS_GAPIC_LIBRARY \
$INCLUDE_SAMPLES \
$DESTINATION_PATH \
$OWLBOT_SHA \
$OWLBOT_PY_PATH \
$REPO_METADATA_PATH
