/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/location/locations.proto

// Protobuf Java Version: 3.25.5
package com.google.cloud.location;

/**
 *
 *
 * <pre>
 * The response message for [Locations.ListLocations][google.cloud.location.Locations.ListLocations].
 * </pre>
 *
 * Protobuf type {@code google.cloud.location.ListLocationsResponse}
 */
public final class ListLocationsResponse
    extends com.google.protobuf.GeneratedMessageLite<
        ListLocationsResponse, ListLocationsResponse.Builder>
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.location.ListLocationsResponse)
    ListLocationsResponseOrBuilder {
  private ListLocationsResponse() {
    locations_ = emptyProtobufList();
    nextPageToken_ = "";
  }

  public static final int LOCATIONS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.google.cloud.location.Location> locations_;
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.cloud.location.Location> getLocationsList() {
    return locations_;
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  public java.util.List<? extends com.google.cloud.location.LocationOrBuilder>
      getLocationsOrBuilderList() {
    return locations_;
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  @java.lang.Override
  public int getLocationsCount() {
    return locations_.size();
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  @java.lang.Override
  public com.google.cloud.location.Location getLocations(int index) {
    return locations_.get(index);
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  public com.google.cloud.location.LocationOrBuilder getLocationsOrBuilder(int index) {
    return locations_.get(index);
  }

  private void ensureLocationsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.google.cloud.location.Location> tmp = locations_;
    if (!tmp.isModifiable()) {
      locations_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
    }
  }

  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  private void setLocations(int index, com.google.cloud.location.Location value) {
    value.getClass();
    ensureLocationsIsMutable();
    locations_.set(index, value);
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  private void addLocations(com.google.cloud.location.Location value) {
    value.getClass();
    ensureLocationsIsMutable();
    locations_.add(value);
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  private void addLocations(int index, com.google.cloud.location.Location value) {
    value.getClass();
    ensureLocationsIsMutable();
    locations_.add(index, value);
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  private void addAllLocations(
      java.lang.Iterable<? extends com.google.cloud.location.Location> values) {
    ensureLocationsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(values, locations_);
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  private void clearLocations() {
    locations_ = emptyProtobufList();
  }
  /**
   *
   *
   * <pre>
   * A list of locations that matches the specified filter in the request.
   * </pre>
   *
   * <code>repeated .google.cloud.location.Location locations = 1;</code>
   */
  private void removeLocations(int index) {
    ensureLocationsIsMutable();
    locations_.remove(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  private java.lang.String nextPageToken_;
  /**
   *
   *
   * <pre>
   * The standard List next-page token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    return nextPageToken_;
  }
  /**
   *
   *
   * <pre>
   * The standard List next-page token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNextPageTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nextPageToken_);
  }
  /**
   *
   *
   * <pre>
   * The standard List next-page token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @param value The nextPageToken to set.
   */
  private void setNextPageToken(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    nextPageToken_ = value;
  }
  /**
   *
   *
   * <pre>
   * The standard List next-page token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  private void clearNextPageToken() {

    nextPageToken_ = getDefaultInstance().getNextPageToken();
  }
  /**
   *
   *
   * <pre>
   * The standard List next-page token.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @param value The bytes for nextPageToken to set.
   */
  private void setNextPageTokenBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nextPageToken_ = value.toStringUtf8();
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.cloud.location.ListLocationsResponse parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.cloud.location.ListLocationsResponse parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.google.cloud.location.ListLocationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.google.cloud.location.ListLocationsResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * The response message for [Locations.ListLocations][google.cloud.location.Locations.ListLocations].
   * </pre>
   *
   * Protobuf type {@code google.cloud.location.ListLocationsResponse}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.cloud.location.ListLocationsResponse, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.location.ListLocationsResponse)
      com.google.cloud.location.ListLocationsResponseOrBuilder {
    // Construct using com.google.cloud.location.ListLocationsResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.cloud.location.Location> getLocationsList() {
      return java.util.Collections.unmodifiableList(instance.getLocationsList());
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    @java.lang.Override
    public int getLocationsCount() {
      return instance.getLocationsCount();
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */

    @java.lang.Override
    public com.google.cloud.location.Location getLocations(int index) {
      return instance.getLocations(index);
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder setLocations(int index, com.google.cloud.location.Location value) {
      copyOnWrite();
      instance.setLocations(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder setLocations(
        int index, com.google.cloud.location.Location.Builder builderForValue) {
      copyOnWrite();
      instance.setLocations(index, builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder addLocations(com.google.cloud.location.Location value) {
      copyOnWrite();
      instance.addLocations(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder addLocations(int index, com.google.cloud.location.Location value) {
      copyOnWrite();
      instance.addLocations(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder addLocations(com.google.cloud.location.Location.Builder builderForValue) {
      copyOnWrite();
      instance.addLocations(builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder addLocations(
        int index, com.google.cloud.location.Location.Builder builderForValue) {
      copyOnWrite();
      instance.addLocations(index, builderForValue.build());
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder addAllLocations(
        java.lang.Iterable<? extends com.google.cloud.location.Location> values) {
      copyOnWrite();
      instance.addAllLocations(values);
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder clearLocations() {
      copyOnWrite();
      instance.clearLocations();
      return this;
    }
    /**
     *
     *
     * <pre>
     * A list of locations that matches the specified filter in the request.
     * </pre>
     *
     * <code>repeated .google.cloud.location.Location locations = 1;</code>
     */
    public Builder removeLocations(int index) {
      copyOnWrite();
      instance.removeLocations(index);
      return this;
    }

    /**
     *
     *
     * <pre>
     * The standard List next-page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @return The nextPageToken.
     */
    @java.lang.Override
    public java.lang.String getNextPageToken() {
      return instance.getNextPageToken();
    }
    /**
     *
     *
     * <pre>
     * The standard List next-page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @return The bytes for nextPageToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNextPageTokenBytes() {
      return instance.getNextPageTokenBytes();
    }
    /**
     *
     *
     * <pre>
     * The standard List next-page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(java.lang.String value) {
      copyOnWrite();
      instance.setNextPageToken(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * The standard List next-page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      copyOnWrite();
      instance.clearNextPageToken();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The standard List next-page token.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextPageTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.location.ListLocationsResponse)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.google.cloud.location.ListLocationsResponse();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "locations_", com.google.cloud.location.Location.class, "nextPageToken_",
              };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0208"
                  + "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.google.cloud.location.ListLocationsResponse> parser =
              PARSER;
          if (parser == null) {
            synchronized (com.google.cloud.location.ListLocationsResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.google.cloud.location.ListLocationsResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:google.cloud.location.ListLocationsResponse)
  private static final com.google.cloud.location.ListLocationsResponse DEFAULT_INSTANCE;

  static {
    ListLocationsResponse defaultInstance = new ListLocationsResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ListLocationsResponse.class, defaultInstance);
  }

  public static com.google.cloud.location.ListLocationsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListLocationsResponse> PARSER;

  public static com.google.protobuf.Parser<ListLocationsResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
