on:
  push:
    branches:
      - main
  pull_request:
    # Changes to these directories do not directly affect the downstream libraries
    paths-ignore:
      - gapic-generator-java/**
      - library_generation/**
      - showcase/**
      - test/**

name: Downstream Check
jobs:
  downstream-compatibility:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        repo:
          - google-cloud-java
          - java-bigtable
          - java-bigquery
          - java-bigquerystorage
          - java-datastore
          - java-firestore
          - java-logging
          - java-logging-logback
          - java-pubsub
          - java-pubsublite
          - java-spanner-jdbc
          - java-spanner
          - java-storage
          - java-storage-nio
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: mvn -version
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils
      - name: Test helper scripts
        run: ./.kokoro/presubmit/common_test.sh
      - name: Perform downstream compatibility testing
        run: REPOS_UNDER_TEST="${{ matrix.repo }}" ./.kokoro/presubmit/downstream-compatibility.sh
