# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# GitHub action job to test core java library features on
# downstream client libraries before they are released.
name: Hermetic library generation upon generation config change through pull requests
on:
  pull_request:

env:
  REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
  GITHUB_REPOSITORY: ${{ github.repository }}
jobs:
  should_run_library_generation:
    runs-on: ubuntu-latest
    steps:
    - name: Determine whether the pull request comes from a fork
      id: determine_fork
      shell: bash
      run: |
        set -x
        if [[ "${GITHUB_REPOSITORY}" != "${REPO_FULL_NAME}" ]]; then
          echo "This PR comes from a fork. Skip library generation."
          echo "should_run=false" >> $GITHUB_OUTPUT
        else
          echo "should_run=true" >> $GITHUB_OUTPUT
        fi
  library_generation:
    runs-on: ubuntu-latest
    needs: should_run_library_generation
    if: needs.should_run_library_generation.outputs.should_run == 'true'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.CLOUD_JAVA_BOT_TOKEN }}
    - name: Install Maven modules
      shell: bash
      run: |
        git checkout "${HEAD_REF}"
        mvn install -B -ntp -DskipTests -Dclirr.skip -Dcheckstyle.skip
      env:
        HEAD_REF: ${{ github.head_ref }}
    - name: Build image
      shell: bash
      run: |
        GENERATOR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -pl gapic-generator-java)
        echo "GENERATOR_VERSION=${GENERATOR_VERSION}" >> "$GITHUB_ENV"
        docker build \
          -f .cloudbuild/library_generation/library_generation.Dockerfile \
          -t gcr.io/cloud-devrel-public-resources/java-library-generation:"${GENERATOR_VERSION}" \
          .
    - uses: ./.github/scripts
      with:
        base_ref: ${{ github.base_ref }}
        head_ref: ${{ github.head_ref }}
        image_tag: ${{ env.GENERATOR_VERSION }}
        token: ${{ secrets.CLOUD_JAVA_BOT_TOKEN }}
