name: librariangen CI

on:
  push:
    branches: [ main ]
    paths:
      - 'internal/librariangen/**'
  pull_request:
    paths:
      - 'internal/librariangen/**'
permissions:
  contents: read

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "internal/librariangen/go.mod"

      - name: Display Go version
        run: go version

      - name: Run Go tests
        run: go test ./...
        working-directory: internal/librariangen

      - name: Build Docker image
        run: docker build -t librariangen-test ./internal/librariangen

      - name: Run version command
        id: version
        run: |
          output=$(docker run --rm -e GOOGLE_SDK_JAVA_LOGGING_LEVEL=quiet librariangen-test --version)
          echo "version_output=$output" >> $GITHUB_OUTPUT

      - name: Verify version
        run: |
          version_output="${{ steps.version.outputs.version_output }}"
          if [[ ! "$version_output" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version format is incorrect. Got: $version_output"
            exit 1
          fi
          echo "Version check passed. Version is $version_output"
