name: Periodic dependency analyze
on:
  schedule:
  # Run at 02:00 UTC on 1st day in January, April, July, and October.
  - cron: '0 2 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  Periodic-dependency-analyze:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    - name: Install modules
      shell: bash
      run: |
        mvn clean install -V --batch-mode --no-transfer-progress -DskipTests
    - name: Generate dependency report against Java shared dependencies
      shell: bash
      run: |
        mvn clean verify -Dskip.surefire.tests -f java-shared-dependencies/dependency-analyzer/pom.xml
