#!/usr/bin/env bash
# Convenience wrapper of gapic generator java that uses the current working
# directory as the classpath. It assumes the location of the generator jar
set -e

# the script is running in google-cloud-java/googleapis.
JAR_PATH=$(pwd)

exec java -classpath "${JAR_PATH}"/../../library_gen_out/gapic-generator-java.jar com.google.api.generator.Main
